# Generated by Django 2.1.7 on 2021-04-14 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('drinks', 'drinks'), ('entrees', 'entress'), ('Appetizers', 'Appetizers'), ('treats', 'treats')], max_length=60),
        ),
    ]
