# Generated by Django 2.1.7 on 2021-04-15 21:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20210414_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='type',
            field=models.CharField(choices=[('treats', 'treats'), ('entrees', 'entress'), ('drinks', 'drinks'), ('Appetizers', 'Appetizers')], max_length=60),
        ),
    ]
